# NOTE: Unless you are chrsmith, you probably will want to
# change this App ID.
application: swift-catfish-511

version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.application
