# NOTE: Unless you are chrsmith, you probably will want to
# change this App ID.
application: test-0609-p2d

version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: helloworld.application
